apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: xiaoxiedocker/demo-nginx:1e51bb2f95d217e8d339ed12bf10be424f819fd2
        ports:
        - containerPort: 80
